### PR TITLE
Fix indent of tags without tag name when using renderFormatted()

### PR DESCRIPTION
**Pull request by obecker**
https://github.com/tipsy/j2html/issues/173

Off topic: Set execute flag on mvnw

### CODE REVIEW

**Comment by tipsy** [comment]
@sembler could you review this?

**Review by sembler — APPROVED** [review]
Looks good to me.  Thanks for including a test!  Eventually we'll want to address this deeply nested logic.  Perhaps as we look into #159.

@tipsy I assume that there is no concern over the maven wrapper (mvnw) having execute permissions as Maven intended?

**Comment by tipsy** [comment]
Thanks @obecker and @sembler!

> @tipsy I assume that there is no concern over the maven wrapper (mvnw) having execute permissions as Maven intended?

I'm not concerned about that, I trust mvnw. Ideally it should be in a different PR, but it's not a big deal, I'll just merge this as is :)

**Comment by obecker** [comment]
> Looks good to me. Thanks for including a test! Eventually we'll want to address this deeply nested logic. Perhaps as we look into #159.

Hi @sembler,
I case you haven't noticed yet, I touched this logic in https://github.com/tipsy/j2html/pull/178

**Pull request merged**
