### PR TITLE
Add method to get number of children of ContainerTag

### PR DESCRIPTION
**Pull request by maztan**

### CODE REVIEW

**Comment by tipsy** [comment]
Could you explain why/when this is useful?

**Comment by maztan** [comment]
Yes, I created a ContainerTag that I populated later in the code depending on some conditions. In the end, the tag could still end up empty (depending on the conditions), in which case I would not like to display it at all. That's why I need children count (or at least get to know if the tag is empty or not).

**Comment by tipsy** [comment]
Ideally the HTML creation should be declarative, could you should me the code?

It sounds like you want something like this:

```java
String result= div(
    iff(items.size() > 0, ul(
        each(items, item -> li(item.property)) 
    ))
).render();
```

**Comment by tipsy** [comment]
@maztan ?

**Comment by maztan** [comment]
Yes, sorry. You are using a collection "items" in your example code. I was using a "div" ContainerTag directly and trying to add it to my output document structure if the div was not empty. Yes, your code will work for me but it adds this extra step of creating a collection and later populating a ContainerTag with it.

**Comment by tipsy** [comment]
@maztan Please show me your code, and I'll see if it can be solved with the current API.

**Comment by maztan** [comment]
Something like this:

            ContainerTag bodyTag = body();
		ContainerTag div1 = div();
		
		if(condition1) {
			div1.with(span().withText("Some content"));
		}
		
		if(condition2) {
			div1.with(span().withText("Some content"));
		}
		
		if(condition3) {
			div1.with(span().withText("Some content"));
		}
		
		if(!div1.isEmpty()) {
			bodyTag.with(div1);
		}
```

**Comment by tipsy** [comment]
The idiomatic way of writing this in j2html would be:
```java
public static void main(String[] args) {
    boolean b1 = false, b2 = true, b3 = false;
    iff(b1 || b2 || b3, body(
        div(
            iff(b1, span("Content 1")),
            iff(b2, span("Content 2")),
            iff(b3, span("Content 3"))
        )
    ));
}
```
Which would produce `<body><div><span>Content 2</span></div></body>`

**Comment by maztan** [comment]
This would work for my simple example. What if I have like 10 conditions and other code that does not render any content or add any tags between those condition checks ("ifs")? This gets messy and complicated. The easiest would be to just be able to treat ContainerTag as a collection (it contains a List anyway I believe).

**Comment by tipsy** [comment]
I can merge the PR if you feel strongly about it, but I'm still interested to see how the approach I outlined becomes complicated. It would be helpful if you could post your actual code example, so I can see if I can make any improvements to j2html that will solve the problem more idiomatically than creating temporary elements. 
My goal with j2html is to make HTML creation in Java as declarative (and as close to HTML) as possible, and asking a tag in html how many children it has can't be done.

**Comment by maztan** [comment]
I can't really show you the actual code but it is already getting awful:

```
iff(b1 || b2 || b3, body(
        div(
            iff(b1, span("Content 1")),
            iff(b2, span("Content 2")),
            iff(b3, span("Content 3"))
        )
    ));
```

The conditions are checked  times here for example. Isn't this nicer?:

```
ContainerTag div1 = div();
if(b1) div1.with(span("Content 1"));
if(b2) div1.with(span("Content 2"));
if(b3) div1.with(span("Content 3"));

ContainerTag body = body();
if(!div1.isEmpty()) body.with(div1);
```

This is much more flexible in my (humble) opinion. I have worked around the problem that this pull request was supposed to fix but I like your library very much and would love to see it go in the direction I have shown in the example above or at least make it possible to write code like this.

**Comment by tipsy** [comment]
> I have worked around the problem that this pull request was supposed to fix but I like your library very much and would love to see it go in the direction I have shown in the example above or at least make it possible to write code like this.

Thanks. The library won't go in this direction, as I strongly disagree with this way of doing things. If you're making HTML in Java, you should (in my opinion) try to get the code as similar to actual HTML as possible.

I will merge the PR though. Thanks for giving your opinion and defending your position, I appreciate it!

**Pull request merged**
