### PR TITLE
#135 issue - the constructor is escaping the text, but the setter doesn't

### PR DESCRIPTION
**Pull request by emanueltrandafir**
#135  the constructor of Attribute was escaping the it's string 'value', but the setter of the class wasn't.

so this was working ok:
``` p().withClass("bar\"baz") ```

while this wasn't:
``` p().withClass("foo").withClass("bar\"baz") ```

### CODE REVIEW

**Comment by tipsy** [comment]
Could you flip the test to do `assertEquals` (instead of `not`)?

**Comment by emanueltrandafir** [comment]
@tipsy sure, I have changed them now and commited.

**Comment by emanueltrandafir** [comment]
Hi, @tipsy is it everything ok now? Thanks.

**Comment by tipsy** [comment]
I'll have another look tomorrow :)

**Comment by tipsy** [comment]
Seems to be a conflicting file though.

**Comment by emanueltrandafir** [comment]
> Looks fine, you just have to fix the conflict :)

Hi,

I have made the update and fixed the conflicts today.

Thanks.

**Comment by emanueltrandafir** [comment]
@tipsy Hello, sorry for bothering, if everything is ok, can we merge it before other commits/changes to the master?

thanks! :)

**Comment by tipsy** [comment]
Sorry about the late reply @emanueltrandafir ! It seems the change also includes the other major refactoring that also happened: `+5,553 −2,580`. This is probably easy to fix by rebasing, but I don't feel comfortable merging it since I don't know what exactly is in it.

**Comment by emanueltrandafir** [comment]
@tipsy no problem. I see someone already fixed the same thing 8 days ago and the PR was merged. I think this can be closed

**Comment by tipsy** [comment]
@emanueltrandafir sorry about that, there's been an unusual amount of traffic on the project lately. Thank you anyway :)

**Pull request closed without merging**
