### PR TITLE
Add ability to change text escaper implementation

### PR DESCRIPTION
**Pull request by sbezkostnyi**
Based on discussion in #69, this pull request adds ability for user to provide another implementation of text escaping.

To do so you can either implement `TextEscaper` interface or use lambda expression and assign it to `Config.textEscaper`.

### CODE REVIEW

**Comment by tipsy** [comment]
Nice, thanks!

**Comment by sbezkostnyi** [comment]
May I ask you to release new version in the near future? I want to use this feature :)

**Comment by tipsy** [comment]
Sure, give me a minute.

**Comment by tipsy** [comment]
`1.1.0` should be out now @sbezkostnyi

**Comment by sbezkostnyi** [comment]
Great, thanks.

**Pull request merged**
