### PR TITLE
Add possibility to remove an Attribute value and add convenient method for "data-" prefixed attributes

### PR DESCRIPTION
**Pull request by mikeleber**
This pr consist of two parts.

1. Make it possible to add and remove an attr value (e.g. add/remove CSS Class)
2. Add a convenient method for "data-" prefixed custom attributes

### CODE REVIEW

**Comment by tipsy** [comment]
@mikeleber @sembler previously I've always felt very strongly about not introducing `add` or `remove` into the API, but to keep it to `set`, because I wanted the API to be as declarative as possible. But the decision is yours @sembler.

**Comment by mikeleber** [comment]
I understand your intention about the declarative way but it make some things complicated on the other side (not only for me, i found some posts in the Issues Section "withClass should append class, not replace"). In this case on my side :-) I need a more flexible way to deal with the attr-content and for this add/remove is necessary. What do you think?

**Comment by sembler** [comment]
Your request would be the start of a paradigm change for this library.  So we need to have a really good justification for doing it.  What is it about your problem/program that makes it difficult to construct HTML in a declarative fashion?  Please provide examples if you can.  If not, can you tell us the flow of your process?

Note that if you intend to modify the contents of Tags after their initial creation, then it signals that you're using the tag structure as your model instead of as a view of the model.  Other libraries have tried to allow that, and it always seemed to create more problems than it solved.

**Comment by mikeleber** [comment]
This is a common szenario for me. A hierarchy of renderer.

 public class NodeRenderer() {
        public void render(Tag htmlElemet, Node node) {
            htmlElemet.withCSS("SOMEHTML");
        }
    }
    public class LeafNodeRenderer() extends NodeRenderer {
        public void render(Tag htmlElemet, Node node) {
            super.render(htmlElemet,node);
            htmlElemet.withCSS("LEAF_ELEMENT");
            if(node.hasAlert()){
                htmlElemet.withCSS("ALERT");
            }
        }
    }
    public class StringNodeRenderer() extends LeafNodeRenderer {
        public void render(Tag htmlElemet, Node node) {
            super.render(htmlElemet,node);
            htmlElemet.withCSS("STRING_FIELD");
        }
    }
    public class RegexedNodeRenderer() extends StringNodeRenderer {
        public void render(Tag htmlElemet, Node node) {
            super.render(htmlElemet,node);
            htmlElemet.withCSS("REGEXED");
        }
    }

For sure it´s possible to set the css classes another way but this is more handy for me and performs much better. 

One thing more! I prefer an open way. This means, give the developer the greatest possible freedom in doing things but tell him about the risk! If he is s smart guy he will know what he is doing.

**Comment by mikeleber** [comment]
Possible solution could be a Lambda backdoor :-)    

    public T appendAttrValue(String name, String value, TriFunction <String,String, ArrayList<Attribute>,T> function) {
        function.apply(name,value,attributes);
        return self();
    }
 @FunctionalInterface
    interface TriFunction<A,B,C,R> {

        R apply(A a, B b, C c);

        default <V> TriFunction<A, B, C, V> andThen(
            Function<? super R, ? extends V> after) {
            Objects.requireNonNull(after);
            return (A a, B b, C c) -> after.apply(apply(a, b, c));
        }
    }

**Comment by sembler** [comment]
Reading between the lines of your example, you're rendering a graph of hierarchical nodes using a inheritance chain.  I assume more is done than simply setting CSS attributes, but it seems like all of the logic for choosing which value(s) to set for your CSS styling could be condensed into a single method without the need for inheritance.  But the devil is in the details, so what is the requirement that you are implementing that needs to use inheritance like this? And how are you matching the renderer to the node in this example?

As for openness, I do agree that having a library that supports broad usage patterns is nice... until you have to maintain and evolve that library.  So we have to take a more cautious approach to ensure that we aren't digging ourselves into a hole.  Similarly, just knowing about the risks doesn't mean that you won't be faced with reworking your implementation if we are forced to undo such decisions to keep the library viable in the future.

**Comment by mikeleber** [comment]
You are right, i am rendering a complex tree generated from an XML or an JSON Schema. But i go much further, i am including a rule engine (Apache jexl) enabling me to set css classes at runtime based on User behaviour and much more. The class hierachy was only a little part of  how i want to use it. One possible solution for me is to fork your project and open your library for my needs If this ist ok for you?

**Pull request closed without merging**
