### PR TITLE
java 6 support: removed diamond operators, apply version in pom.xml

### PR DESCRIPTION
**Pull request by szyszy**
Please create a release to support JDK 6 as well.
Actually I would not like you to merge this to master, but I could not specify formally / don't have any other way to tell you that I would like to have a separate release (tag) that supports JDK 6.

### CODE REVIEW

**Comment by tipsy** [comment]
Seems like a small enough change, but I'm a little sad that you're still using Java 6.

> Actually I would not like you to merge this to master

Why not? It won't impact anyone using Java789 ?

**Comment by szyszy** [comment]
Actually I'm sad too..
For me a dedicated released version would be good enough, then I could use your library as a simple dependency again.
I was just thinking it could affect others because I needed to change the source/target version to 1.6 in the pom.xml therefore you cannot use java 7/8 features anymore (diamond operators, lambdas, anything).
Maybe merging my change and make a release from that and then "revert" my changes to be compatible again with java 8 could be the way to go.
Anyway, I leave it to you how you deal with this pull request, thanks for your effort :)

**Comment by tipsy** [comment]
I forgot about some Java8 dependencies I can't get rid of without losing functionality (not in your PR).
If you want, we could create a Java6 branch that you could depend on via [jitpack](https://jitpack.io/)?

**Comment by tipsy** [comment]
@szyszy Can you try to build master and see if it works for you?

**Comment by tipsy** [comment]
Please test and see if it works in your project:
```xml
<dependency>
    <groupId>com.j2html</groupId>
    <artifactId>j2html</artifactId>
    <version>1.0.0-RC</version>
</dependency>
```

**Comment by szyszy** [comment]
Sorry for the delay.
Today I checked your java 6 version (1.0.0-RC), it works fine for me on a JDK 6 environment.
Thanks!

**Pull request closed without merging**
