### PR TITLE
Appendable

### PR DESCRIPTION
**Pull request by kicktipp**
Without this PR:

```
RenderPerformanceTest.staticPerfomanceTest: 
[measured 50000 out of 50200 rounds, threads: 2 (physical processors: 8)]
round: 0.00 [+- 0.00], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], 
GC.calls: 11, GC.time: 0.08, time.total: 2.46, time.warmup: 0.06, 
time.bench: 2.40
```
With this PR: 

```
RenderPerformanceTest.staticPerfomanceTest: 
[measured 50000 out of 50200 rounds, threads: 2 (physical processors: 8)]
round: 0.00 [+- 0.00], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], 
GC.calls: 6, GC.time: 0.03, time.total: 0.91, time.warmup: 0.07, 
time.bench: 0.84
```
It saves 66% of CPU cycles and 50% of GC!

Pretty amazing. I never thought it would enhance performance so much as j2html is already pretty fast. We use it already in production and had 10% benefit over very optimized JSP files.

Additional comments:

I added a super class Renderer to have Attribute extend from it.

### CODE REVIEW

**Comment by tipsy** [comment]
Before
```
RenderPerformanceTest.staticPerfomanceTest: 
[measured 50000 out of 50200 rounds, threads: 2 (physical processors: 8)]
round: 0.00 [+- 0.00], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00], 
GC.calls: 15, GC.time: 0.04, time.total: 2.91, time.warmup: 0.09, 
time.bench: 2.82
```
 
After
```
RenderPerformanceTest.staticPerfomanceTest:
[measured 50000 out of 50200 rounds, threads: 2 (physical processors: 8)]
round: 0.00 [+- 0.00], round.block: 0.00 [+- 0.00], round.gc: 0.00 [+- 0.00],
GC.calls: 9, GC.time: 0.03, time.total: 1.31, time.warmup: 0.04,
time.bench: 1.28
```

Very cool.

**Comment by tipsy** [comment]
>  I added a super class Renderer to have Attribute extend from it.

Why not just let attribute extend DomContent ?

The `render(Appendable writer)` javadoc has to be rewritten to something like

```
   /**
     * Render the DomContent and it's children using the supplied writer
     *
     * @param writer the current writer
     */
```

**Comment by kicktipp** [comment]
Because Attribute extends from Renderer, too, but should not be DomContent 
as you should not add an attribute as a child to div for example.

regards
Janning



Am 1. Dezember 2017 20:25:03 schrieb David <notifications@github.com>:

**Comment by tipsy** [comment]
> as you should not add an attribute as a child to div for example.

Right. An empty `DomContent` extending `Renderer` doesn't look very clean to me though. What about creating an interface `Renderable`, which both `DomContent` and `Attribute` implement?

```
public interface Renderable {

    /**
     * Create a StringBuilder and use it render the Renderable and it's content
     */
    default String render() {
        StringBuilder stringBuilder = new StringBuilder();
        try {
            render(stringBuilder);
        } catch (IOException e) {
            throw new RuntimeException(e.getMessage(), e);
        }
        return stringBuilder.toString();
    }

    /**
     * Render the Renderable and it's children using the supplied writer
     *
     * @param writer the current writer
     */
    void render(Appendable writer) throws IOException;
}
```

Might need some refactoring at a later point.

**Comment by kicktipp** [comment]
Added interface Renderable. Looks fine

**Comment by kicktipp** [comment]
This PR does not compile as the projects tries to be java 1.6 compatible. This is a nice effort but in my opinion useless as most people should use java8. Please choose:

A. Removing java 1.6 retrolambda
B. Removing interface with default implementation

I will fix it according to your decision. My vote is for removing java 1.6 compatibility as this is easier and bugs like this does not happen again

**Comment by tipsy** [comment]
I can remove retro-lambda when I get home (or you can remove it in this PR).
Someone wanted support for 1.6 in the past, but they can use one of the current releases.

**Comment by kicktipp** [comment]
Done. If you like it, you can merge it now.

**Comment by tipsy** [comment]
Something is wrong with `Tag.java` 🤔

**Comment by kicktipp** [comment]
I fixed the formatting problem. Sorry for this. I am using different machines and not all machines were configured with your code style. Annoying  that isn't a good solution available for formatting aspects.

**Comment by tipsy** [comment]
> I fixed the formatting problem. Sorry for this. I am using different machines and not all machines were configured with your code style. Annoying that isn't a good solution available for formatting aspects.

No problem. I'll run everything through my formatter again to see if there are any differences in our configs.

**Pull request merged**
