### PR TITLE
support osgi meta data in provided jar.

### PR DESCRIPTION
**Pull request by Naxos84**
I like to use this lib in an osgi environment.
Therefore I added the necessary plugins during build to provide OSGI meta data in MANIFEST.MF

### CODE REVIEW

**Comment by tipsy** [comment]
Hmm.. I don't really know antyhing about osgi, but I'm guessing you've built this locally and tested it?

**Comment by Naxos84** [comment]
Of course I tested it locally.
Just for reference:
https://www.ibm.com/support/knowledgecenter/en/SSEQTP_8.5.5/com.ibm.websphere.osgi.doc/ae/ra_bundle_mf.html

If you check the created MANIFEST.MF in target/classes/META-INF then you
see that the unnecessary things are generated.

David <notifications@github.com> schrieb am Di., 17. Apr. 2018, 16:47:

**Comment by tipsy** [comment]
@Naxos84 could this affect backwards compatibility in any way?

**Comment by Naxos84** [comment]
It should not. Cause every info that was present in old MANIFEST is still
available.
But to be honest I'm not sure for 100% (Just for 99% or so)...

David <notifications@github.com> schrieb am Di., 17. Apr. 2018, 21:55:

**Comment by tipsy** [comment]
Alright. From what I read it seems it should be fine.

**Comment by tipsy** [comment]
Thanks!

**Comment by tipsy** [comment]
This has been released in 1.3.0 now.

**Comment by tipsy** [comment]
> Btw. If you don't want to export every package from this project, please let me know and we may be able to fix that too.

Are you talking about jigsaw modules or osgi?

**Pull request merged**
