### PR TITLE
Remove manual tags, use only generated tags

### PR DESCRIPTION
**Pull request by obecker**
- change html, head, body from manual to generated tags
- restore compatibility with j2html 1.4.0
- fix https://github.com/tipsy/j2html/issues/185

### CODE REVIEW

**Comment by tipsy** [comment]
> restore compatibility with j2html 1.4.0

Nice ! Providing this is merged, should I release 1.5.0 tomorrow?

**Comment by obecker** [comment]
@tipsy I have no concerns. However, I wonder if there is a CHANGELOG (didn't found one). The new release would not be 100% compatible. For example, I'm using the type `ContainerTag`, which is now a generic type. So the compiler will show compile warnings, and if you use `-Werror` as compiler flag (like I do), the compiler will even stop with an error. This is not a big deal and can easily be fixed, but I think it should be documented somewhere.
Also the examples in the documentation (https://j2html.com/examples.html) should reflect the new type system (instead of just `Tag` it should be `Tag<?>` or more specific `InputTag`/`ButtonTag`). And finally the example demonstrating the `Config` class needs an update.

**Review by sembler — CHANGES_REQUESTED** [review]
Looks excellent to me.

One minor request.  In CONTRIBUTING.md, line 83, can we be more specific with the locations of the Tag classes: `library/src/main/java/j2html/tags/specialized/generated/` instead of `library/src/main/java/j2html/tags/specialized/`. Or clarify that the classes are within some package under that location.

Thanks!

**Comment by obecker** [comment]
Done. I wonder if it makes sense to remove that `generated` subpackage altogether and have all classes simply in `specialized`?
Anyway, for a 2.\* version I would like to turn `code_gen` into a maven (or gradle) plugin that generates its code into `src/generated/java` which is not under git control. Then we might reconsider an appropriate package structure.

**Review by sembler — APPROVED** [review]

**Comment by sembler** [comment]
It does make sense to discard the extra layer in the package hierarchy, and I'd approve if you wanted to before releasing 1.5. Doing code generation as a build step would be an excellent step forward as well.

**Pull request merged**
