### PR TITLE
Added TextContainer for HTML Fragments

### PR DESCRIPTION
**Pull request by thomaspz**
I added a TextContainer Tag to generate Text-Fragments with inline HTML.

### CODE REVIEW

**Comment by tipsy** [comment]
@thomaspz, the font-tag is [not valid HTML5](http://www.w3schools.com/tags/tag_font.asp), it's common to use CSS for font-styling now.
If you really want to use the font-tag, you can use ContainerTag("font") and use attr manually, but I don't recommend it, and I won't merge this PR, sorry.
I'm not sure what the purpose of text-container is. The library already has .text() and .unsafeHtml(), what more does the TextContainer offer?

**Comment by thomaspz** [comment]
Sorry, that was my fault. I only want to push the textContainer. I didn't know that every commit would combined in one pull request. 
The TextContainer offer me the fluent api to generate a fragment of html. 

The call 
TagContainer.textcontainer().with(TagCreator.text("Hello "), TagCreator.b("World"),
				TagCreator.text("! some other Text"), TagCreator.i("italic word")).render();

Creates this fragment with html escaping. A nice way with fluent api to generate my html-fragment. 

Hello <b>World</b>! some other Text<i>italic word</i>

I don't see a way to get it with unsafeHtml.

**Comment by tipsy** [comment]
I see. Are you injecting this HTML somewhere else using JavaScript? I never really considered people wanting to create content not surrounded by tags. I would wrap it in a p or a span:

    p().with(
        text("Hello "),
        b("World"), text("! some other Text"),
        i("italic word")
    ).render();

But I think this is the biggest weakness of my library.. Since it's so much harder to read than HTML, and you have to keep track of white-spaces over multiple lines, I prefer just doing:

    unsafeHtml("Hello <b>World</b>! some other Text<i>italic word</i>").render();

Btw, I really encourage you to use static imports in stead of referencing TagCreator all the time :)

**Comment by thomaspz** [comment]
Thank you. I want to use it to pre-generate formated text for Birt Reporting with an comfortable fluent way. I couldn't use surounded tags there. I see no advantage of the second way. Than I can do it completet without your library.

**Comment by tipsy** [comment]
I see. I will think about adding this functionality, but I can't promise anything :)
When you say Birt, is this what you mean? https://en.wikipedia.org/wiki/BIRT_Project

**Pull request closed without merging**
