### PR TITLE
Do not indent textarea contents

### PR DESCRIPTION
**Pull request by mwanji**
Addresses problem raised in #102 

Let me know if there are any style / testing issues with this PR.

### CODE REVIEW

**Comment by tipsy** [comment]
Thanks @mwanji, I had a look at this fix a long time ago, this is what I had locally: https://github.com/tipsy/j2html/pull/114. My fix is a little broken, ideally we shouldn't render "empty space" for the `each` tag. Maybe you can improve it?

**Comment by mwanji** [comment]
@tipsy I integrated your changes from #114 piecemeal here, as it was easier for me to understand it that way. The main difference is that the extra space and level of indentation have been removed from the RenderFormattedText::testFormattedTags_each unit test expectation.

I also replaced ImmutableList::of with Arrays::asList, to be able to remove Google Guava from the dependencies.

**Comment by tipsy** [comment]
This has been released in 1.3.0 now.

**Comment by mwanji** [comment]
Cool, thanks.

**Pull request merged**
