### PR TITLE
add font tag

### PR DESCRIPTION
**Pull request by codedrinker**
Our project is using your tool, that's very cool way to generate html template, and we need font tag to warp text, so could you accept my request or add one? thanks a lot.

### CODE REVIEW

**Comment by tipsy** [comment]
Is there a specific reason why you have to use the `<font>` tag instead of spans with classes?
I don't really want to add non-HTML5 tags to j2html. (You can use tag("font") for now).

**Comment by codedrinker** [comment]
We use j2html to generate html for Android WebView, because we wanna preview html on mobile device, but the Android WebView doesn't support <span> tag. We just wanna add some styles for words, if we use <div> tag, we have to adjust many styles for it.
[The support list for WebView](https://commonsware.com/blog/Android/2010/05/26/html-tags-supported-by-textview.html)

**Comment by tipsy** [comment]
This seems to be a pretty unusual case, please use `tag("font")` for now. 
Let's leave the issue open to see if anyone else requests this though.

**Comment by codedrinker** [comment]
Ok,Thanks a lot.

**Pull request closed without merging**
